### ISSUE TITLE
standardizing compute environments

### ISSUE THREAD

**Issue by soniapolt** [cjnani16/deeprfs_tf#3]
- [x] common data

- [x] general path function

- [x] reproducible virtual environments based on requirements.txt
    - Should be able to `pip install -r requirements.txt` to fully reproduce virtualenv

**Comment by cjnani16** [comment]
Thus far I can only anticipate running this on Nyla and 'Amoxicillin' so I guess some sort of switch which sets paths to data on the fs based on hostname is going to be very achievable. 

Also generating the `requirements.txt` will be hugely helpful!

**Comment by eshedmargalit** [comment]
Just so it's recorded somewhere, here's how I reproduce virtual environments across machines:

1. Enter the virtual environment you want to clone, however you normally do (whether conda or virtualenv or pyenv)
```
pyenv activate some_environment
```
2. Save the installed pip packages to a requirements file
```
pip freeze > requirements.txt
```

3. Commit the new requirements file
```
git add requirements.txt
git commit -m "adds requirements file for virtual environment"
```

4. Clone or pull the repo on other machine via `git pull`

5. Create a new virtual environment on the other machine with conda, virtualenv, pyenv, etc
```
pyenv virtualenv some_environment
```
Enter the new virtualenv if needed.

6. Install the requirements cloned from the repo
```
pip install -r requirements.txt
```

And done!

**Comment by cjnani16** [comment]
Awesome thank you for these instructions!!

--
Sent from mobile: 510.940.3695

________________________________

**Comment by eshedmargalit** [comment]
To-dos 2019115
- [ ] Add to general path function a checkpoints path
